# generated by datamodel-codegen:
#   filename:  http://localhost:3000/api/docs-json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional


@dataclass
class HealthDto:
    version: str


@dataclass
class RelaySettingsDto:
    port: float
    downloadLimit: float
    uploadLimit: float
    connectionsLimit: float
    torrentConnectionsLimit: float
    enableUpnpAndNatpmp: bool


@dataclass
class UpdateRelaySettingsDto:
    port: Optional[float] = None
    downloadLimit: Optional[float] = None
    uploadLimit: Optional[float] = None
    connectionsLimit: Optional[float] = None
    torrentConnectionsLimit: Optional[float] = None
    enableUpnpAndNatpmp: Optional[bool] = None


class TrackerEnum(Enum):
    ncore = 'ncore'
    bithumen = 'bithumen'
    majomparade = 'majomparade'
    insane = 'insane'


@dataclass
class TrackerMetaDto:
    value: TrackerEnum
    label: str
    requiresFullDownload: bool
    url: str
    detailsPath: str


class LanguageEnum(Enum):
    hu = 'hu'
    en = 'en'


@dataclass
class LanguageMetaDto:
    value: LanguageEnum
    label: str


class ResolutionEnum(Enum):
    field_2160p = '2160p'
    field_1080p = '1080p'
    field_720p = '720p'
    field_576p = '576p'
    field_540p = '540p'
    field_480p = '480p'


@dataclass
class ResolutionMetaDto:
    value: ResolutionEnum
    label: str


class VideoQualityEnum(Enum):
    dolby_vision = 'dolby-vision'
    hdr10_ = 'hdr10+'
    hdr10 = 'hdr10'
    hlg = 'hlg'
    sdr = 'sdr'


@dataclass
class VideoQualityMetaDto:
    value: VideoQualityEnum
    label: str


class AudioQualityEnum(Enum):
    truehd = 'truehd'
    dts_hd_ma = 'dts-hd-ma'
    ddp = 'ddp'
    dts = 'dts'
    dd = 'dd'
    aac = 'aac'
    unknown = 'unknown'


@dataclass
class AudioQualityMetaDto:
    value: AudioQualityEnum
    label: str


class AudioSpatialEnum(Enum):
    dolby_atmos = 'dolby-atmos'
    dts_x = 'dts-x'


@dataclass
class AudioSpatialMetaDto:
    value: AudioSpatialEnum
    label: str


class SourceEnum(Enum):
    disc_remux = 'disc-remux'
    disc_rip = 'disc-rip'
    web_dl = 'web-dl'
    web_rip = 'web-rip'
    broadcast = 'broadcast'
    theatrical = 'theatrical'
    unknown = 'unknown'


@dataclass
class SourceMetaDto:
    value: SourceEnum
    label: str


@dataclass
class KodiImdbStreamDto:
    torrentName: str
    fileName: str
    seeders: float
    size: str
    tracker: TrackerMetaDto
    languages: List[LanguageMetaDto]
    resolution: ResolutionMetaDto
    videoQualities: List[VideoQualityMetaDto]
    source: SourceMetaDto
    url: str
    audioQuality: Optional[AudioQualityMetaDto] = None
    audioSpatial: Optional[AudioSpatialMetaDto] = None


@dataclass
class KodiImdbStreamsDto:
    streams: List[KodiImdbStreamDto]
    errors: List[str]


class Name(Enum):
    search = 'search'
    genre = 'genre'
    skip = 'skip'


@dataclass
class ManifestExtraDto:
    name: Name
    isRequired: Optional[bool] = None
    options: Optional[List[str]] = None
    optionsLimit: Optional[float] = None


class Type(Enum):
    movie = 'movie'
    series = 'series'
    channel = 'channel'
    tv = 'tv'


@dataclass
class ManifestCatalog:
    type: Type
    id: str
    name: str
    extra: Optional[List[ManifestExtraDto]] = None


class Type1(Enum):
    text = 'text'
    number = 'number'
    password = 'password'
    checkbox = 'checkbox'
    select = 'select'


@dataclass
class ManifestConfigDto:
    key: str
    type: Type1
    default: Optional[str] = None
    title: Optional[str] = None
    options: Optional[List[str]] = None
    required: Optional[str] = None


@dataclass
class ManifestBehaviorHintsDto:
    adult: Optional[bool] = None
    p2p: Optional[bool] = None
    configurable: Optional[bool] = None
    configurationRequired: Optional[bool] = None


@dataclass
class ManifestDto:
    id: str
    name: str
    description: str
    version: str
    resources: List[Dict[str, Any]]
    types: List[Type]
    catalogs: List[ManifestCatalog]
    idPrefixes: Optional[List[str]] = None
    addonCatalogs: Optional[List[ManifestCatalog]] = None
    config: Optional[List[ManifestConfigDto]] = None
    background: Optional[str] = None
    logo: Optional[str] = None
    contactEmail: Optional[str] = None
    behaviorHints: Optional[ManifestBehaviorHintsDto] = None


@dataclass
class BehaviorHintsDto:
    notWebReady: bool
    countryWhitelist: Optional[List[str]] = None
    bingeGroup: Optional[str] = None
    filename: Optional[str] = None


@dataclass
class StremioStreamDto:
    name: str
    description: str
    url: str
    behaviorHints: BehaviorHintsDto


@dataclass
class StremioStreamsResponseDto:
    streams: List[StremioStreamDto]


class MediaTypeEnum(Enum):
    movie = 'movie'
    series = 'series'


class PosterShapeEnum(Enum):
    square = 'square'
    regular = 'regular'
    landscape = 'landscape'


@dataclass
class MetaLinkDto:
    name: str
    category: str
    url: str


@dataclass
class MetaPreviewDto:
    type: Type
    id: str
    name: str
    posterShape: Optional[PosterShapeEnum] = None
    imdb_id: Optional[str] = None
    poster: Optional[str] = None
    background: Optional[str] = None
    logo: Optional[str] = None
    description: Optional[str] = None
    imdbRating: Optional[str] = None
    releaseInfo: Optional[str] = None
    genres: Optional[List[str]] = None
    cast: Optional[List[str]] = None
    director: Optional[List[str]] = None
    links: Optional[List[MetaLinkDto]] = None


@dataclass
class StremioCatalogDto:
    metas: List[MetaPreviewDto]
    cacheMaxAge: Optional[float] = None
    staleRevalidate: Optional[float] = None
    staleError: Optional[float] = None


@dataclass
class MetaTrailerDto:
    ytId: str
    description: str


@dataclass
class MetaVideoDto:
    id: str
    title: str
    released: Optional[str] = None
    thumbnail: Optional[str] = None
    available: Optional[bool] = None
    episode: Optional[float] = None
    season: Optional[float] = None
    trailer: Optional[str] = None
    overview: Optional[str] = None


@dataclass
class MetaDetailBehaviorHintsDto:
    defaultVideoId: Optional[str] = None
    hasScheduledVideos: Optional[bool] = None


@dataclass
class MetaDetailDto:
    type: Type
    id: str
    name: str
    posterShape: Optional[PosterShapeEnum] = None
    imdb_id: Optional[str] = None
    poster: Optional[str] = None
    background: Optional[str] = None
    logo: Optional[str] = None
    description: Optional[str] = None
    imdbRating: Optional[str] = None
    releaseInfo: Optional[str] = None
    genres: Optional[List[str]] = None
    cast: Optional[List[str]] = None
    director: Optional[List[str]] = None
    links: Optional[List[MetaLinkDto]] = None
    released: Optional[str] = None
    year: Optional[str] = None
    trailers: Optional[List[MetaTrailerDto]] = None
    videos: Optional[List[MetaVideoDto]] = None
    runtime: Optional[str] = None
    language: Optional[str] = None
    country: Optional[str] = None
    awards: Optional[str] = None
    website: Optional[str] = None
    behaviorHints: Optional[MetaDetailBehaviorHintsDto] = None
    writer: Optional[List[str]] = None


@dataclass
class MetaDto:
    meta: MetaDetailDto
    cacheMaxAge: Optional[float] = None
    staleRevalidate: Optional[float] = None
    staleError: Optional[float] = None


@dataclass
class PairInitDto:
    userCode: str
    deviceCode: str
    expiresAt: str


@dataclass
class PairStatusRequestDto:
    deviceCode: str


class Status(Enum):
    pending = 'pending'
    linked = 'linked'
    expired = 'expired'


@dataclass
class PairStatusDto:
    status: Status
    token: Optional[str] = None


@dataclass
class KodiIntegrationStreamsParametersQuery:
    season: Optional[float] = None
    episode: Optional[float] = None
