# generated by datamodel-codegen:
#   filename:  https://localhost:7070/api/openapi.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional, Union


@dataclass
class AttributeResponse:
    id: str
    name: str
    short_name: Optional[str] = None
    preference_id: Optional[str] = None


@dataclass
class BehaviorHints:
    country_whitelist: Optional[List[str]] = None
    not_web_ready: Optional[bool] = True
    binge_group: Optional[str] = None
    filename: Optional[str] = None


class ContentType(Enum):
    movie = 'movie'
    series = 'series'
    channel = 'channel'
    tv = 'tv'


class ExtraName(Enum):
    search = 'search'
    genre = 'genre'
    skip = 'skip'


@dataclass
class IndexerDefinitionResponse:
    id: str
    name: str
    url: str
    details_path: str
    requires_full_download: bool


@dataclass
class KodiImdbStreamResponse:
    torrent_name: str
    file_name: str
    seeders: int
    size: str
    indexer: IndexerDefinitionResponse
    media_attributes: List[AttributeResponse]
    url: str


@dataclass
class KodiImdbStreamsResponse:
    streams: List[KodiImdbStreamResponse]
    errors: List[str]


@dataclass
class ManifestBehaviorHints:
    adult: Optional[bool] = None
    p2_p: Optional[bool] = None
    configurable: Optional[bool] = None
    configuration_required: Optional[bool] = None


class ManifestConfigType(Enum):
    text = 'text'
    number = 'number'
    password = 'password'
    checkbox = 'checkbox'
    select = 'select'


@dataclass
class ManifestExtra:
    name: ExtraName
    is_required: Optional[bool] = None
    options: Optional[List[str]] = None
    options_limit: Optional[int] = None


class MediaType(Enum):
    movie = 'movie'
    series = 'series'


@dataclass
class MetaDetailBehaviorHints:
    default_video_id: Optional[str] = None
    has_scheduled_videos: Optional[bool] = None


@dataclass
class MetaLink:
    name: str
    category: str
    url: str


@dataclass
class MetaTrailer:
    yt_id: str
    description: str


@dataclass
class MetaVideo:
    id: str
    title: str
    released: Optional[str] = None
    thumbnail: Optional[str] = None
    available: Optional[bool] = None
    episode: Optional[int] = None
    season: Optional[int] = None
    trailer: Optional[str] = None
    overview: Optional[str] = None


@dataclass
class PairInitResponse:
    user_code: str
    device_code: str
    expires_at: str


@dataclass
class PairStatusResponse:
    status: str
    token: Optional[str] = None


class PosterShape(Enum):
    square = 'square'
    regular = 'regular'
    landscape = 'landscape'


@dataclass
class RelaySettingsResponse:
    port: int
    download_limit: int
    upload_limit: int
    connections_limit: int
    torrent_connections_limit: int
    enable_upnp_and_natpmp: bool


@dataclass
class RelaySettingsUpdateRequest:
    port: Optional[int] = None
    download_limit: Optional[int] = None
    upload_limit: Optional[int] = None
    connections_limit: Optional[int] = None
    torrent_connections_limit: Optional[int] = None
    enable_upnp_and_natpmp: Optional[bool] = None


class ShortManifestResource(Enum):
    catalog = 'catalog'
    meta = 'meta'
    stream = 'stream'
    subtitles = 'subtitles'
    addon_catalog = 'addon_catalog'


@dataclass
class StremioStream:
    name: str
    description: str
    url: str
    behavior_hints: BehaviorHints


@dataclass
class StremioStreams:
    streams: List[StremioStream]


@dataclass
class SuccessResponse:
    success: bool
    message: Optional[str] = None


@dataclass
class ValidationError:
    loc: List[Union[str, int]]
    msg: str
    type: str
    input: Optional[Any] = None
    ctx: Optional[Dict[str, Any]] = None


@dataclass
class KodiFindStreamsParametersQuery:
    season: Optional[int] = None
    episode: Optional[int] = None


@dataclass
class FullManifestResource:
    name: ShortManifestResource
    types: List[ContentType]
    id_prefixes: Optional[List[str]] = None


@dataclass
class HTTPValidationError:
    detail: Optional[List[ValidationError]] = None


@dataclass
class ManifestCatalog:
    type: ContentType
    id: str
    name: str
    extra: Optional[List[ManifestExtra]] = None


@dataclass
class ManifestConfig:
    key: str
    type: ManifestConfigType
    default: Optional[str] = None
    title: Optional[str] = None
    options: Optional[List[str]] = None
    required: Optional[str] = None


@dataclass
class MetaDetail:
    id: str
    type: ContentType
    name: str
    imdb_id: Optional[str] = None
    poster: Optional[str] = None
    poster_shape: Optional[PosterShape] = PosterShape.regular
    background: Optional[str] = None
    logo: Optional[str] = None
    description: Optional[str] = None
    imdb_rating: Optional[str] = None
    release_info: Optional[str] = None
    genres: Optional[List[str]] = None
    cast: Optional[List[str]] = None
    director: Optional[List[str]] = None
    links: Optional[List[MetaLink]] = None
    released: Optional[str] = None
    year: Optional[str] = None
    trailers: Optional[List[MetaTrailer]] = None
    videos: Optional[List[MetaVideo]] = None
    runtime: Optional[str] = None
    language: Optional[str] = None
    country: Optional[str] = None
    awards: Optional[str] = None
    website: Optional[str] = None
    behavior_hints: Optional[MetaDetailBehaviorHints] = None
    writer: Optional[List[str]] = None


@dataclass
class MetaPreview:
    id: str
    type: ContentType
    name: str
    imdb_id: Optional[str] = None
    poster: Optional[str] = None
    poster_shape: Optional[PosterShape] = PosterShape.regular
    background: Optional[str] = None
    logo: Optional[str] = None
    description: Optional[str] = None
    imdb_rating: Optional[str] = None
    release_info: Optional[str] = None
    genres: Optional[List[str]] = None
    cast: Optional[List[str]] = None
    director: Optional[List[str]] = None
    links: Optional[List[MetaLink]] = None


@dataclass
class MetaResponse:
    meta: Union[MetaDetail, Dict[str, Any]]


@dataclass
class StremioCatalogResponse:
    metas: List[MetaPreview]


@dataclass
class Manifest:
    id: str
    name: str
    description: str
    version: str
    resources: List[Union[ShortManifestResource, FullManifestResource]]
    types: List[ContentType]
    catalogs: List[ManifestCatalog]
    id_prefixes: Optional[List[str]] = None
    addon_catalogs: Optional[List[ManifestCatalog]] = None
    config: Optional[List[ManifestConfig]] = None
    background: Optional[str] = None
    logo: Optional[str] = None
    contact_email: Optional[str] = None
    behavior_hints: Optional[ManifestBehaviorHints] = None
