# generated by datamodel-codegen:
#   filename:  http://localhost:3000/api/docs/kodi-json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class TrackerEnum(Enum):
    ncore = 'ncore'
    bithumen = 'bithumen'
    majomparade = 'majomparade'
    insane = 'insane'


@dataclass
class TrackerMetaDto:
    value: TrackerEnum
    label: str
    requiresFullDownload: bool
    url: str
    detailsPath: str


class LanguageEnum(Enum):
    hu = 'hu'
    en = 'en'


@dataclass
class LanguageMetaDto:
    value: LanguageEnum
    label: str


class ResolutionEnum(Enum):
    field_2160p = '2160p'
    field_1080p = '1080p'
    field_720p = '720p'
    field_576p = '576p'
    field_540p = '540p'
    field_480p = '480p'


@dataclass
class ResolutionMetaDto:
    value: ResolutionEnum
    label: str


class VideoQualityEnum(Enum):
    dolby_vision = 'dolby-vision'
    hdr10_ = 'hdr10+'
    hdr10 = 'hdr10'
    hlg = 'hlg'
    sdr = 'sdr'


@dataclass
class VideoQualityMetaDto:
    value: VideoQualityEnum
    label: str


class AudioQualityEnum(Enum):
    truehd = 'truehd'
    dts_hd_ma = 'dts-hd-ma'
    ddp = 'ddp'
    dts = 'dts'
    dd = 'dd'
    aac = 'aac'
    unknown = 'unknown'


@dataclass
class AudioQualityMetaDto:
    value: AudioQualityEnum
    label: str


class AudioSpatialEnum(Enum):
    dolby_atmos = 'dolby-atmos'
    dts_x = 'dts-x'


@dataclass
class AudioSpatialMetaDto:
    value: AudioSpatialEnum
    label: str


class SourceEnum(Enum):
    disc_remux = 'disc-remux'
    disc_rip = 'disc-rip'
    web_dl = 'web-dl'
    web_rip = 'web-rip'
    broadcast = 'broadcast'
    theatrical = 'theatrical'
    unknown = 'unknown'


@dataclass
class SourceMetaDto:
    value: SourceEnum
    label: str


@dataclass
class KodiImdbStreamDto:
    torrentName: str
    fileName: str
    seeders: int
    size: str
    tracker: TrackerMetaDto
    languages: list[LanguageMetaDto]
    resolution: ResolutionMetaDto
    videoQualities: list[VideoQualityMetaDto]
    source: SourceMetaDto
    url: str
    audioQuality: AudioQualityMetaDto | None = None
    audioSpatial: AudioSpatialMetaDto | None = None


@dataclass
class KodiImdbStreamsDto:
    streams: list[KodiImdbStreamDto]
    errors: list[str]
