# generated by datamodel-codegen:
#   filename:  http://localhost:4000/api/docs/kodi-json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional


class MediaTypeEnum(Enum):
    movie = 'movie'
    series = 'series'


@dataclass
class PublicCatalogDto:
    mediaType: MediaTypeEnum
    id: str
    title: str
    description: str
    createdAt: str
    updatedAt: str


class KodiMediaTypeEnum(Enum):
    movie = 'movie'
    show = 'show'
    season = 'season'
    episode = 'episode'


class Adult(Enum):
    number_0 = 0
    number_1 = 1


@dataclass
class KodiCatalogItemDto:
    mediatype: KodiMediaTypeEnum
    id: float
    imdb_id: str
    rank: Optional[float] = None
    adult: Optional[Adult] = None
    title: Optional[str] = None
    description: Optional[str] = None
    release_year: Optional[float] = None
    language: Optional[str] = None
    spoken_language: Optional[str] = None
    season: Optional[float] = None
    episode: Optional[float] = None


KodiCatalogsFindResponse = List[PublicCatalogDto]


KodiCatalogItemsFindResponse = List[KodiCatalogItemDto]
