# generated by datamodel-codegen:
#   filename:  http://localhost:4000/api/docs/kodi-json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional


class CatalogTypeEnum(Enum):
    auto = 'auto'
    manual = 'manual'


class CatalogVisibilityEnum(Enum):
    public = 'public'
    unlisted = 'unlisted'
    private = 'private'


class CatalogStatusEnum(Enum):
    draft = 'draft'
    published = 'published'
    archived = 'archived'


class MediaTypeEnum(Enum):
    movie = 'movie'
    series = 'series'


@dataclass
class CatalogDto:
    id: str
    title: str
    description: str
    type: CatalogTypeEnum
    visibility: CatalogVisibilityEnum
    status: CatalogStatusEnum
    mediaType: MediaTypeEnum
    isOfficial: bool
    createdAt: str
    updatedAt: str


class KodiMediaTypeEnum(Enum):
    movie = 'movie'
    show = 'show'
    season = 'season'
    episode = 'episode'


class Adult(Enum):
    number_0 = 0
    number_1 = 1


@dataclass
class KodiCatalogItemDto:
    id: float
    imdb_id: str
    mediatype: KodiMediaTypeEnum
    rank: Optional[float] = None
    adult: Optional[Adult] = None
    title: Optional[str] = None
    description: Optional[str] = None
    release_year: Optional[float] = None
    language: Optional[str] = None
    spoken_language: Optional[str] = None
    season: Optional[float] = None
    episode: Optional[float] = None


FindResponse = List[CatalogDto]


FindResponse1 = List[KodiCatalogItemDto]
